name: Token Setup

on:
  push:
    branches:
      - main  # або інша гілка, яку ви використовуєте

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up the token
        run: echo "TOKEN=${{ secrets.MY_BOT_TOKEN }}" >> $GITHUB_ENV

      - name: Run JavaScript Script with Token
        run: |
          node -e "console.log('My Token:', process.env.TOKEN)"
